### ISSUE TITLE
文档指南中个别第三方平台链接失效

### ISSUE THREAD

**Issue by bd-dxg** [timqian/sideproject.guide#5]
在[收费工具](https://sideproject.guide/making-money#%E6%94%B6%E8%B4%B9%E5%B7%A5%E5%85%B7)这一节中, 面包多的顿顿饭的链接已经失效, 具体信息详见:
https://www.chinaz.com/2022/1028/1461970.shtml
面包多的新网址:https://mbd.pub/

**Comment by timqian** [comment]
似乎没有找到顿顿饭的新地址，如果有人找到，欢迎PR

**Comment by bd-dxg** [comment]
> 似乎没有找到顿顿饭的新地址，如果有人找到，欢迎PR

....我上面不是给了吗
> 面包多的新网址:https://mbd.pub/

**Comment by timqian** [comment]
顿顿饭是面包多做的用于接受赞助的一个产品，本来有自己的网址的
