### ISSUE TITLE
Site Translation

### ISSUE THREAD

**Issue by CLCK0622** [timqian/sideproject.guide#7]
Hello, I (@CLCK0622), @MrWillCom and @aeilot are now working on the english ver. of your site. 
We will finish all the translation work in a week, and if you update your site, you can still remind us and we will always be glad to help.

**Comment by timqian** [comment]
Awesome!!

**Comment by CLCK0622** [comment]
We have finished the first edition of our translation efficiently. 
After proofreading, a draft pull request will be opened. 
The progress can be seen at https://github.com/MrWillCom/sideproject.guide/tree/transl-en.

**Comment by CLCK0622** [comment]
As mentioned in #8 , we nearly finished our translation.
